import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HomePageLayout from "../layout/Layout";

export const poppins = Poppins({
  subsets: ["latin"], // Choose subsets as needed
  weight: ["400", "700"], // Specify the font weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HomePageLayout>{children}</HomePageLayout>
      </body>
    </html>
  );
}
