import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "../core-component/custom-styles.css"
import HomePageLayout from "../layout/Layout";
import "swiper/css";
import 'swiper/css/effect-fade';
import 'swiper/css/autoplay';

export const poppins = Poppins({
  subsets: ["latin"], // Choose subsets as needed
  weight: ["400", "700"], // Specify the font weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "EduForU – Empowering Dreams Beyond Boundaries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/images/favicon.webp" />
      </head>
      <body>
        <HomePageLayout>{children}</HomePageLayout>
      </body>
    </html>
  );
}
