export const AustraliaDetails = {
  bannerTile: "STUDY IN AUSTRALIA",
  title: "Why To Choose Australia As Your Destination",
  about: [
    "Global Popularity: Ranked as the third most popular destination for international students, following the United States and the UK.",
    "Cultural Diversity and Friendliness: Attracts students with its cultural diversity, friendly locals, and high-quality education.",
    "Academic Excellence: Approximately 19 out of 42 Australian universities rank in the top 2% globally.",
    "Quality Assurance: The Australian Quality Assurance Framework ensures universities adhere to the highest educational standards, emphasizing structure and rigor.",
    "Simplified Visa Process: The government’s commitment to attracting international students is reflected in a streamlined visa process, reducing processing times and document requirements.",
    "Safe and Livable Cities: Australian cities boast low crime rates and consistent rankings among the world’s most livable.",
    "Family Accommodation: Dependents (spouse/children) can join, stay, and work (spouse).",
    "Part-Time Work Opportunities: Students are permitted 20 hours of part-time work fortnightly during sessions and 40 hours during breaks.",
    "Flexible Work Permits: Work permits ranging from 1 to 4 years are available for international students.",
    "Immigration Opportunities: Tailored immigration pathways are available for Indian students, enhancing post-study opportunities.",
  ],
  univercityTitle: "TOP UNIVERSITIES OF AUSTRALIA",
  UKUniversity: [
    { image: "/images/Melbourne.svg", link: "University of Melbourne" },
    { image: "/images/Queensland.png", link: "University of Queensland" },
    { image: "/images/Sydney.webp", link: "University of Sydney" },
    { image: "/images/ANU.png", link: "Australian National University" },
    { image: "/images/Monash.png", link: "Monash University" },
    { image: "/images/Wollongong.png", link: "University of Wollongong" },
    { image: "/images/Adelaide.png", link: "University of Adelaide" },
    { image: "/images/UTS.jpg", link: "University of Technology Sydney" },
    { image: "/images/Australia.png", link: "University of Western Australia" },
  ],
  coursesTitle: "TOP COURSES IN AUSTRALIA",
  topCourses: [
    "Master of Business Administration",
    "Accountancy",
    "Agricultural Sciences",
    "Law",
    "Engineering",
    "Earth Sciences and Related Fields",
    "Petroleum and Geosciences",
    "Education",
    "Psychology"
  ],
};
