export const CanadaDetails = {
    bannerTile: "STUDY IN CANADA",
    title: "Why To Choose CANADA As Your Study Destination",
    about: [
      "Top-Tier Universities: Home to prestigious institutions like Oxford, Cambridge, and Russell Group Universities, offering world-class education.",
      "Global Recognition: UK degrees are highly respected worldwide, enhancing international employability.",
      "Language Excellence: Immerse in an English-speaking environment for refined language proficiency.",
      "Cultural Diversity: Experience a rich multicultural society with deep historical and cultural roots.",
      "Research Opportunities: Engage in cutting-edge research in a country known for innovation.",
      "Networking: Build a global network with diverse peers in a prominent hub for international students.",
      "Student Support: Access comprehensive support services and top-notch facilities.",
      "Work Opportunities: Work part-time during studies and full-time during breaks, fostering practical experience.",
      "Post-Study Work: Benefit from post-study work options, allowing stay in the UK after graduation.",
      "Quality of Life: Enjoy a high standard of living and well-developed public services.",
      "Europe Proximity: Convenient travel to explore other European countries.",
      "Student Discounts: Access various discounts for a more affordable student life.",
      "Global Perspective: UK education encourages critical thinking and a global outlook.",
      "Taught Masters: One-year duration for taught Master courses, minimizing time and resource commitment.",
      "Undergraduate Programs: In England, Wales, and Northern Ireland, most undergraduate degrees last for three years.",
      "Part-Time Jobs: Permissible part-time work on or off-campus during sessions (20 hours) and breaks (40 hours), with a minimum hourly wage of £7.70.",
      "English-Language Requirement: Flexibility in waiving English language exam scores like IELTS, TOEFL, etc., enhancing accessibility for diverse students.",
    ],
    univercityTitle: "Top Universities In CANADA",
    UKUniversity: [
      { image: "/images/Ucl.png", link: "University College London" },
      { image: "/images/Oxford.png", link: "University of Oxford" },
      { image: "/images/Imperial.png", link: "Imperial College London" },
      { image: "/images/Cambridge.jpg", link: "University of  Cambridge" },
      { image: "/images/Edinburgr.png", link: "University Of Edinburgh" },
      { image: "/images/Warwick.jpg", link: "University of Warwick" },
      { image: "/images/Bristol.png", link: "University of Bristol" },
      { image: "/images/Glasgow.jpg", link: "University of Glasgow" },
      { image: "/images/Manchester.png", link: "University of Manchester" },
    ],
    coursesTitle: "Top Courses To Study In CANADA",
    topCourses: [
      "Medicine",
      "Engineering",
      "Medicine-related Subjects",
      "Veterinary Science",
      "Education Studies",
      "Law",
      "Architecture",
      "Biological Sciences",
      "Economics",
      "Business and Management",
    ],
  };
  