export const CanadaDetails = {
  bannerTile: "STUDY IN CANADA",
  title: "Why To Choose CANADA As Your Study Destination",
  about: [
    "Global Recognition: Consistently ranked among the best countries worldwide, currently holding the #1 position for quality of life.",
    "Education Investment: Canada prioritizes education, leading in per capita spending among G-8 countries and ranking in the top three in the OECD.",
    "Safety and Peace: Recognized as one of the safest nations globally, listed sixth in the Global Peace Index in 2018. International students enjoy the same rights as Canadian citizens.",
    "Diverse Opportunities: Universities offer unique experiences, including international exchanges, co-op work programs, and a vibrant array of extracurricular activities and athletics.",
    "Co-op Work Experience: Many institutions provide co-op work experience programs, allowing students to integrate academic semesters with practical work directly related to their degree.",
    "Affordable Tuition: Known for having some of the lowest university tuition fees among English-speaking countries, making education accessible.",
    "Post-Graduation Work Permit Program (PWPP): Graduates can stay and work in Canada for up to three years after completing their studies through the PWPP, offering a pathway to gain international work experience and apply for permanent residency.",
    "Immigration Opportunities: Canada’s welcoming policies provide a pathway for international students to contribute to and settle in the country permanently.",
    "Quality Healthcare: Access to a high-quality healthcare system, contributing to overall well-being.",
    "Natural Beauty and Outdoor Activities: Canada’s breathtaking landscapes offer opportunities for outdoor adventures, enhancing the overall student experience.",
    "Multicultural Society: Embraces diversity, fostering a multicultural environment that enriches the student experience.",
  ],
  univercityTitle: "Top Universities In CANADA",
  UKUniversity: [
    { image: "/images/Toronto.jpg", link: " University of Toronto" },
    { image: "/images/Columbia.png", link: "The University of British Columbia" },
    { image: "/images/Waterloo.png", link: "University of Waterloo" },
    { image: "/images/McMatster.png", link: "McMaster University" },
    { image: "/images/Ottawa.png", link: "University of Ottawa" },
    { image: "/images/Western.png", link: "Western University" },
    { image: "/images/MgGrill.png", link: "McGill University" },
    { image: "/images/Alberta.png", link: "University of Alberta" },
    { image: "/images/Montreal.png", link: "University of Montreal" },
  ],
  coursesTitle: "Top Courses To Study In CANADA",
  topCourses: [
    "Master Real Estate Business Management",
    "Business Administration",
    "Computer Science",
    "Digital Media Master",
    "Engineering",
    "Master programs",
    "Agriculture and Environmental Sciences",
    "Finance",
  ],
};
