export const IrelandDetails = {
  bannerTile: "STUDY IN IRELAND",
  title: "Why To Choose Ireland As Your Study Destination",
  about: [
    "European Union Member: Sole English-speaking country in the European Union, providing a unique advantage for international students.",
    "One-Year Taught Master’s Courses: Accelerated master’s programs streamline education, saving time and expenses.",
    "Single Intake in September: Limited competition for post-graduation jobs due to the singular intake, primarily in September.",
    "World-Class Education System: Ireland ranks in the top twenty globally for higher education achievements.",
    "Generous Scholarships: Hundreds of scholarships awarded annually to international students.",
    "Prestigious Institutions: Home to renowned institutions like Trinity College Dublin, akin to Oxford and Cambridge.",
    "Corporate Attraction: Ireland’s 12.5% Corporation Tax attracts top global companies to establish European headquarters.",
    "FDI Hub: Identified as the top destination for U.S. foreign direct investment, fostering economic opportunities.",
    "Leading Exporter: Ireland excels in exporting pharmaceuticals, medical devices, and software globally.",
    "Government Research Investment: Annual investment of over Euros 782 million in higher education research, leading in various fields.",
    "Safety: Ranked the 10th safest place globally (Global Peace Index 2018), ensuring a secure living environment.",
    "Post-Study Work Options: A two-year post-study work window enhances career prospects for graduates.",
    "Part-Time Work Opportunities: Students allowed 20 hours of part-time work during sessions and 40 hours during breaks, with a minimum wage of 9.80 Euros.",
    "Taught Masters: One-year duration for taught Master courses, minimizing time and resource commitment.",
    "Work Permit and Immigration: Simplified work permit and immigration processes facilitate ease of staying and working post-graduation.",
  ],
  univercityTitle: "TOP UNIVERSITIES IN IRELAND",
  UKUniversity: [
    { image: "/images/Dublin.png", link: "Trinity College Dublin" },
    { image: "/images/DCU.png", link: "Dublin City University" },
    { image: "/images/UCD.png", link: " University College Dublin" },
    { image: "/images/NCI.png", link: " National College of Ireland" },
    { image: "/images/UCC.jpg", link: "University College Cork" },
    { image: "/images/Limerick.png", link: "University of Limerick" },
    { image: "/images/Maynooth.png", link: "Maynooth University" },
    { image: "/images/AIT.jpg", link: " Institute of Technology Sligo" },
    { image: "/images/RCSI.jpg", link: "Royal College of Surgeons in Ireland" },
  ],
  coursesTitle: "Top Courses To Study In United Kingdom",
  topCourses: [
    "MA Global History",
    "International affairs",
    "MA Philosophy",
    "Msc Agricultural Extension and Innovation",
    "Master of Business Administration",
    "Master’s in Cybersecurity",
    "Masters in digital marketing",
    "ME Energy Systems",
  ],
};
